/**:
  controller_manager:
    ros__parameters:
      update_rate: 31   # close to Webots 32 ms

  joint_state_broadcaster:
    ros__parameters:
      type: joint_state_broadcaster/JointStateBroadcaster

  diff_drive_controller:
    ros__parameters:
      type: diff_drive_controller/DiffDriveController
      publish_rate: 50.0
      base_frame_id: base_link
      left_wheel_names: ["left wheel motor"]
      right_wheel_names: ["right wheel motor"]
      wheel_separation: 0.160
      wheel_radius: 0.033
      use_stamped_vel: false
      cmd_vel_timeout: 0.5
      odom_frame_id: odom
      enable_odom_tf: true
